### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by CPhilipse** [shx996/react-native-tiny-toast#11]
Every time the toast is being triggered it shows this warning: 

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: ToastContainer

Will this be fixed?

**Comment by phanbien9x** [comment]
I have the same error with react native 0.61.5. Please update lifecycles to fix that!

**Comment by andordavoti** [comment]
Any update on this? Will it be fixed?

**Comment by shawwal** [comment]
May be you can try this, https://github.com/shx996/react-native-tiny-toast/pull/15 .. I remove componentWillReceiveProps and change it to componentDidUpdate, the warning it's gone after I change that and it still can be used as usual @andordavoti @CPhilipse @phanbien9x

**Comment by shx996** [comment]
Has been merged, thanks for your contributions

**Comment by fdelavra** [comment]
I have the same problem with ComponentWillMount. Is it possible to merge again? thanks
